name: Node.js CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (CI side)
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user

          # Clona o repositório se ainda não existir
          if [ ! -d "deck-of-cards-repository" ]; then
            git clone https://github.com/barbara-oliveira-projects/deck-of-cards-repository.git
          fi

          cd deck-of-cards-repository

          # Puxa a última versão do main
          git pull origin main

          # Instala dependências de produção
          npm install --omit=dev

          # Garante que o PM2 esteja instalado
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          # Inicia ou reinicia a aplicação
          pm2 restart app || pm2 start npm --name "app" -- start

          # Salva o estado atual dos processos do PM2
          pm2 save

          # Configura PM2 para iniciar com o sistema (isso precisa ser executado manualmente uma vez):
          # sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ec2-user --hp /home/ec2-user
