name: Node.js CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (CI side)
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/deploy
          
          # Clona o repositório se não existir
          if [ ! -d "deck-of-cards-repository" ]; then
            git clone https://github.com/barbara-oliveira-projects/deck-of-cards-repository.git
          fi

          cd deck-of-cards-repository

          # Puxa últimas alterações
          git pull origin main

          # Instala dependências sem as dev
          npm install --omit=dev

          # Reinicia com PM2
          pm2 restart all || pm2 start npm --name "deck-app" -- start
